### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by steveklabnik** [mixonic/ember-community-versions#4]
Is this project open source? It'd be useful to replicate to other communities, but without a license, it's all rights reserved.

**Comment by mixonic** [comment]
1000% yes. Just added `LICENSE` with the MIT

**Comment by steveklabnik** [comment]
:confetti_ball:

Thanks!

**Comment by mixonic** [comment]
@steveklabnik There are a few ideas floating around on how to improve things as well- such as possibly using a JS widget instead of an iframe. IMO it is nice to keep it as a static server and Jekyll so we can easily manage contributions via GH (and if we want fancier UIs just built them in JS against the GH API or generated JSON files), but I could be convinced otherwise. @machty wants to attempt a solution using referrers, for example.

If you pick this up for Rust and start to run with it, we should try to pool resources. :rocket:

**Comment by steveklabnik** [comment]
For sure. I'll keep you all posted ❤️❤️❤️
